[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "tailcloud-sdk"
version = "0.1.0"
description = "TailCloud SDK for Python"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

authors = [
    { name = "TailCloud" }
]

dependencies = []

[tool.setuptools.packages.find]
where = ["src"]